package com.company.studios.studio4.anotherExample;


public class MenuItem {
    // fields
    private double price;
    private String description;
    private String category;
    private boolean isNew;

    // constructors, overloaded, and empty
    public MenuItem(double price, String description, String category, boolean isNew) {
        this.price = price;
        this.description = description;
        this.category = category;
        this.isNew = isNew;
    }

    public MenuItem(double price, String description, String category) {
        this(price, description, category, true);
    }

    public MenuItem() { };

    // methods
    public  void printOne () {
        System.out.println(this.toString().replaceAll(this.category, ""));
    }

    public static void printHeading() {
        System.out.println("Price \t Description");
    }



    // overrides
    @Override
    public String toString() {
        String current = this.price + "\t" + this.description + "\t" + this.category;
        String addNew = "***NEW***";
        if(this.isNew) {
            return current.concat(addNew);
        }
        return current;
    }

    // below are autogenerated overrides
    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }


    // getters and setters
    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public boolean isNew() {
        return isNew;
    }

    public void setNew(boolean aNew) {
        isNew = aNew;
    }
}
